### ISSUE TITLE
server

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Silly511/KeepingInventory#2]
https://gist.github.com/329bb6e0aa42aa0ebb2fdacdab2e9739
https://gist.github.com/74d41e103a43f08b966010e112f34017

**Comment by Fadenfire** [comment]
I think you have two versions of keeping inventory installed at once.

**Comment by mik900** [comment]
I have the same problem. i do not have two versions of keeping inventory installed at once. I have only installed "Keeping Inventory 1.9-2.1.jar". Only after I removed the folder "net" inside the "KeepingInventory-1.9-2.1.jar", it works fine. I suspect there are two versions in the "jar".

**Comment by SvEgiiVEteR** [comment]
@mik900 so there.. I thought crashes look...
        KeepingInventory{1.8} [Keeping Inventory] RES_KeepingInventory-1.7.10-2.1
        KeepingInventory{2.1} [Keeping Inventory] RES_KeepingInventory-1.7.10-2.1

**Comment by mik900** [comment]
@SvEgiiVEteR 
I use the MC1.9 version of KeepingInventory. My crasches looks like yours but for MC1.9:
`KeepingInventory{2.0} [Keeping Inventory] (KeepingInventory-1.9-2.1)`
`KeepingInventory{2.1} [Keeping Inventory] (KeepingInventory-1.9-2.1)`

In my case in the "KeepingInventory-1.9-2.1.jar" are three folder (META-INF, net, silly511) and one file (mcmod.info). I removed the entire "net" folder. Now it works fine for me.

**Comment by SvEgiiVEteR** [comment]
@mik900 I also helped remove this folder.

**Comment by Fadenfire** [comment]
Ok your right it is a bug I'll release a fix this afternoon. Sorry about saying you had two versions of keeping inventory installed, it's just that that error basically sates you have version 1.8 and version 2.1 installed.

**Comment by Fadenfire** [comment]
Uploaded a hotfix to [curseforge](http://minecraft.curseforge.com/projects/keeping-inventory/files), go and get it.
